USE [master]
GO
/****** Object:  Database [dbSQL]    Script Date: 28/12/2020 23:33:32 ******/
CREATE DATABASE [dbSQL]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dbSQL', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\dbSQL.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'dbSQL_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\dbSQL_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [dbSQL] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbSQL].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [dbSQL] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [dbSQL] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [dbSQL] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [dbSQL] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [dbSQL] SET ARITHABORT OFF 
GO
ALTER DATABASE [dbSQL] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [dbSQL] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [dbSQL] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [dbSQL] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [dbSQL] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [dbSQL] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [dbSQL] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [dbSQL] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [dbSQL] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [dbSQL] SET  DISABLE_BROKER 
GO
ALTER DATABASE [dbSQL] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [dbSQL] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [dbSQL] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [dbSQL] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [dbSQL] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [dbSQL] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [dbSQL] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [dbSQL] SET RECOVERY FULL 
GO
ALTER DATABASE [dbSQL] SET  MULTI_USER 
GO
ALTER DATABASE [dbSQL] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [dbSQL] SET DB_CHAINING OFF 
GO
ALTER DATABASE [dbSQL] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [dbSQL] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [dbSQL] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [dbSQL] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'dbSQL', N'ON'
GO
ALTER DATABASE [dbSQL] SET QUERY_STORE = OFF
GO
USE [dbSQL]
GO
/****** Object:  User [NT SERVICE\MSSQLServerOLAPService]    Script Date: 28/12/2020 23:33:32 ******/
CREATE USER [NT SERVICE\MSSQLServerOLAPService] FOR LOGIN [NT SERVICE\MSSQLServerOLAPService] WITH DEFAULT_SCHEMA=[dbo]
GO
/****** Object:  Table [dbo].[DimCliente]    Script Date: 28/12/2020 23:33:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DimCliente](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](50) NOT NULL,
	[ciudad] [varchar](50) NOT NULL,
	[pais] [varchar](20) NOT NULL,
 CONSTRAINT [PK_DimCliente] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DimEmpleado]    Script Date: 28/12/2020 23:33:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DimEmpleado](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[apellido] [varchar](50) NOT NULL,
	[informe] [int] NOT NULL,
 CONSTRAINT [PK_DimEmpleado] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DimProducto]    Script Date: 28/12/2020 23:33:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DimProducto](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](50) NOT NULL,
	[categoria] [varchar](50) NOT NULL,
 CONSTRAINT [PK_DimProducto] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DimProveedor]    Script Date: 28/12/2020 23:33:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DimProveedor](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nombreCompania] [varchar](20) NOT NULL,
	[pais] [varchar](20) NOT NULL,
 CONSTRAINT [PK_DimProveedor] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DimTiempo]    Script Date: 28/12/2020 23:33:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DimTiempo](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[fecha] [date] NOT NULL,
	[anio] [int] NOT NULL,
	[trimestre] [int] NOT NULL,
	[mes] [varchar](20) NOT NULL,
	[dia] [int] NOT NULL,
 CONSTRAINT [PK_DimTiempo] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Ventas]    Script Date: 28/12/2020 23:33:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ventas](
	[productoID] [int] NOT NULL,
	[clienteID] [int] NOT NULL,
	[empleadoID] [int] NOT NULL,
	[tiempoID] [int] NOT NULL,
	[proveedorID] [int] NOT NULL,
	[precio] [float] NOT NULL,
	[cantidad] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Ventas]  WITH CHECK ADD  CONSTRAINT [FK_Ventas_DimCliente] FOREIGN KEY([clienteID])
REFERENCES [dbo].[DimCliente] ([id])
GO
ALTER TABLE [dbo].[Ventas] CHECK CONSTRAINT [FK_Ventas_DimCliente]
GO
ALTER TABLE [dbo].[Ventas]  WITH CHECK ADD  CONSTRAINT [FK_Ventas_DimEmpleado] FOREIGN KEY([empleadoID])
REFERENCES [dbo].[DimEmpleado] ([id])
GO
ALTER TABLE [dbo].[Ventas] CHECK CONSTRAINT [FK_Ventas_DimEmpleado]
GO
ALTER TABLE [dbo].[Ventas]  WITH CHECK ADD  CONSTRAINT [FK_Ventas_DimProducto] FOREIGN KEY([productoID])
REFERENCES [dbo].[DimProducto] ([id])
GO
ALTER TABLE [dbo].[Ventas] CHECK CONSTRAINT [FK_Ventas_DimProducto]
GO
ALTER TABLE [dbo].[Ventas]  WITH CHECK ADD  CONSTRAINT [FK_Ventas_DimProveedor] FOREIGN KEY([proveedorID])
REFERENCES [dbo].[DimProveedor] ([id])
GO
ALTER TABLE [dbo].[Ventas] CHECK CONSTRAINT [FK_Ventas_DimProveedor]
GO
ALTER TABLE [dbo].[Ventas]  WITH CHECK ADD  CONSTRAINT [FK_Ventas_DimTiempo] FOREIGN KEY([tiempoID])
REFERENCES [dbo].[DimTiempo] ([id])
GO
ALTER TABLE [dbo].[Ventas] CHECK CONSTRAINT [FK_Ventas_DimTiempo]
GO
USE [master]
GO
ALTER DATABASE [dbSQL] SET  READ_WRITE 
GO
